dyn3:
	proc  dynamic3 code=kr_c 
	cl /I "D:\oracle\product\10.2.0\client_1\precomp\public" /c /Tc dynamic3.c		
	link dynamic3.obj orasql10.lib \
		/libpath:"D:\oracle\product\10.2.0\client_1\precomp\LIB" /out:main.exe 




