######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 24 00:42:26 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += firstqt.cpp
