######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 19 12:08:10 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
